# Generated by Django 5.1.7 on 2025-04-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_qtd_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nome',
            new_name='usuario',
        ),
    ]
