# Generated by Django 5.1.7 on 2025-04-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_rename_nome_pedido_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='image',
            new_name='imagem',
        ),
    ]
